# Generated by Django 5.0.2 on 2024-05-16 11:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.ManyToManyField(default="customer", related_name="roles", to="users.role"),
        ),
    ]
