# Generated by Django 5.0.2 on 2024-05-16 19:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_remove_user_role_delete_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(choices=[("admin", "Admin"), ("user", "User")], default="user", max_length=128),
        ),
    ]
