# Generated by Django 4.2.7 on 2024-05-17 16:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(choices=[("admin", "admin"), ("user", "user")], default="user", max_length=128),
        ),
    ]
