# Generated by Django 4.2.7 on 2024-05-17 17:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_customer"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Customer",
        ),
    ]
