# Generated by Django 4.2.7 on 2024-05-17 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="main_photo",
        ),
        migrations.AddField(
            model_name="post",
            name="description",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="postgallery",
            name="post",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="blogs", to="blog.post"),
        ),
    ]
