# Generated by Django 4.2.7 on 2024-05-17 18:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_remove_post_main_photo_post_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="main_photo",
            field=models.ImageField(default=1, upload_to="post/"),
            preserve_default=False,
        ),
    ]
