# Generated by Django 4.2.7 on 2024-05-18 14:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_alter_review_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="color",
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
