# Generated by Django 4.2.7 on 2024-05-18 16:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_product_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="main_image",
            field=models.ImageField(blank=True, null=True, upload_to="product/"),
        ),
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(null=True, unique=True),
        ),
    ]
