# Generated by Django 4.2.7 on 2024-05-18 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0010_alter_customer_first_name_alter_customer_last_name"),
        ("products", "0004_product_main_image_alter_product_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="favouriteproducts",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="customer_like", to="users.customer"
            ),
        ),
    ]
